hchb_platform:
  target: dev

  outputs:

    # ==========================================================
    # DEVELOPMENT
    # ==========================================================
    dev:
      type: snowflake

      account: ex52281.east-us.azure
      user: TF_CICD_SVC
      role: TF_CICD_ROLE
      warehouse: COMPUTE_WH

      database: HC_RAW
      schema: HCHB

      threads: 4

      authenticator: SNOWFLAKE_JWT

      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      client_session_keep_alive: false


    # # ==========================================================
    # # PRODUCTION
    # # ==========================================================
    prod:
      type: snowflake

      account: ex52281.east-us.azure
      user: TF_CICD_SVC
      role: TF_CICD_ROLE
      warehouse: COMPUTE_WH

      database: HC_RAW
      schema: HCHB

      threads: 10

      authenticator: SNOWFLAKE_JWT

      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      client_session_keep_alive: false


