{{ config(
    database="HC_FUSION",
    schema="STG_SILVER",
    alias="HCHB_BRANCHES_CLEANSED",
    materialized="incremental",
    unique_key="BRANCH_CODE",
    incremental_strategy="merge",
    tags=["RAW", "STG_SILVER"]
) }}

SELECT
    BRANCH_CODE,
    BRANCH_NAME,
    BRANCH_STATE,
    BRANCH_CITY,
    BRANCH_ZIP,
    BRANCH_PHONE,
    BRANCH_PARENTCODE,
    BRANCH_FRIENDLYNAME,
    BRANCH_ACTIVE,
    BRANCH_COUNTRY,
    BRANCH_INSERTDATE,
    BRANCH_LASTUPDATE,
    BRANCH_BRANCHGL,
    BRANCH_CONTACT,
    BRANCH_CORPOFFICE,
    BRANCH_EMAIL,
    BRANCH_FAX,
    BRANCH_FEDERALTAXID,
    BRANCH_HOSSTATELICENSE,
    BRANCH_IDENTITY,
    BRANCH_INCLUDEINALL,
    BRANCH_INCLUDEONPHYSICIANWEBSITE,
    BRANCH_LATITUDE,
    BRANCH_LATLONGMETHOD,
    BRANCH_LONGITUDE,
    BRANCH_PARENT,
    BRANCH_PROVIDERNUMBER,
    BRANCH_REGID,
    BRANCH_RESOURCEID,
    BRANCH_SCHEDULINGPHONE,
    BRANCH_SMSHELPPHONE,
    BRANCH_STATELICENSE,
    BRANCH_STREET,
    BRANCH_ADDRESSMAPPED,
    BRANCH_COUNTY,
    BRANCH_FEDERALID,
    BRANCH_HHMEDICAREEXPECTEDGMLUPA,
    BRANCH_HHMEDICAREEXPECTEDGMOUTLIER,
    BRANCH_HHMEDICAREEXPECTEDGMSTANDARD,
    BRANCH_HHMEDICAREEXPECTEDGMTHERAPY,
    BRANCH_ISHOSPICEINPATIENTUNIT,
    BRANCH_MCCM,
    BRANCH_MEDALOGIXBACKOFFICEINTEGRATION,
    BRANCH_PAYROLLCODE,
    BRANCH_PAYROLLCODE2,
    BRANCH_REMITTANCEID,
    BRANCH_RSLID,
    BRANCH_SILENTGPSATPCVISITEND,
    BRANCH_SILENTGPSATPCVISITSTART,
    BRANCH_TZID,
    BRANCH_WEBADDRESS,
    _CDC_OP,
    _CDC_TS,
    INSERTED_DATE,
    INSERTED_BY,
    UPDATED_DATE
FROM {{ ref('HC_RAW_HCHB_BRANCHES') }}

WHERE BRANCH_CODE IS NOT NULL

{% if is_incremental() %}
AND INSERTED_DATE >
(
    SELECT COALESCE(MAX(INSERTED_DATE),'1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}

QUALIFY ROW_NUMBER() OVER
(
    PARTITION BY BRANCH_CODE
    ORDER BY INSERTED_DATE DESC
)=1
